### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by JeroenDeDauw** [lcobucci/clock#12]
I'd like to use this in a (Wikimedia) project that for silly reasons is using something in between PHP 5.6 and 7.0. Hence I can't without a PHP 5.6 compatible version.

This component states that it needs 7.2 but it looks like it is 7.1 compatible. Also looks like a 5.6 version can be created by removing some type hints. Is a PR that creates such a version welcome?

**Comment by lcobucci** [comment]
@JeorenDeDauw thanks for looking into using this pkg, however I prefer to not support older versions of PHP...

It's a mix of reasons but the main ones are: maintance cost and personal beliefs. 

Regarding the latter, I like to think that as a maintainer I can help the community to move forward by not actively maintaining versions different than the latest stable. It might be silly but I've been seeing the effects in some places.

To address your issue I'd recommend you to do as the awesome @localheinz which forked this repo to add PHP 7.0 support (or talk to him to check if his willing to support PHP 5.6).

I hope you understand my point 😁

**Comment by localheinz** [comment]
@JeroenDeDauw 

Feel free to take a look at https://github.com/localheinz/clock.

Let me know if I can help!

**Comment by localheinz** [comment]
@JeroenDeDauw 

Would https://github.com/localheinz/clock/pull/7 be helpful?

**Comment by lcobucci** [comment]
Closing here since @localheinz is willing to maintain PHP 5.6 too. Thank you both :+1:
