### ISSUE TITLE
Minor version update to 1.2 adds breaking change (php 7.2)

### ISSUE THREAD

**Issue by RobvH** [lcobucci/clock#14]
A minor version shouldn't, in theory, cause breaking changes, but increasing the requirement to PHP 7.2 (while defensible) breaks existing installs. I think it's a great idea to keep up to date with the latest but lots of builds are still using 7.1.

**Comment by lcobucci** [comment]
@RobvH as explained in https://github.com/lcobucci/clock/issues/11#issuecomment-415762997, bumping dependencies is not a BC break. Composer is smart enough to pick the correct version for the system.
