### ISSUE TITLE
Question: Clock usage in entities

### ISSUE THREAD

**Issue by ragboyjr** [lcobucci/clock#28]
A common pattern I use is storing timestamps like createdAt, processedAt, etc etc type datetimes in an entity like the following:

```php
class Acme
{
  private $createdAt;
  private $processedAt;

  public function __construct() {
    $this->createdAt = new \DateTimeImmutable();
  }

  public function process(): void {
    $this->processedAt = new \DateTimeImmutable();
  }
}
```

I'm curious how you normally would approach a situation like this for your entities?

It feels a bit clunky to pass in a Clock object to my entities to record the time something happened:

```php
class Acme
{
  private $createdAt;
  private $processedAt;

  public function __construct(Clock $clock) {
    $this->createdAt = $clock->now();
  }

  public function process(Clock $clock): void {
    $this->processedAt = $clock->now();
  }
}
```

Seems like a supplemental global helper and/or singleton which would allow you to swap implementations during testing would be a big help in DX/ergonomics for this library.

e.g.

```php
function clock(array $params = []): Clock {
  static $clock;
  if (isset($params['globalClock'])) {
   $clock = $params['globalClock'];
  }
  if (!$clock) {
    $clock = new SystemClock();
  }
  return $clock;
}
```

This would then allow easily access to the clock globally, but also allow for swapping different implementations at runtime.

**Comment by lcobucci** [comment]
@ragboyjr I usually pass the clock to the entity, an alternative is passing the `DatetimeImmutable` object to it and leaving the clock instance to the caller of the entity's methods.

I honestly don't recommend the usage of the any global helper/singleton, they create indirection and coupling.
In your particular example, one would have to set the `static $clock` for tests or always pass the `$params` down to entities. That, **to me**, is not a very good design.

Will be closing this one but feel free to add more arguments to the discussion :smile:

**Comment by ragboyjr** [comment]
Passing the date time feels a bit weird since it feels like created at should be tied to instantiation, so clock feels more reasonable. But even then making the clock a hard dependency on the object feels an extra burden.

How do you feel using the clock impacts your usability in your code and tests? I feel like it would just make testing an unnecessary burden

**Comment by lcobucci** [comment]
@ragboyjr that's the thing, I don't feel the impact you're describing is a good justification for shipping something that relies on global state. 

I already had to solve way too many bugs related to global state that I simply discourage its usage, especially on a library - even if it potentially improves the DX.

The idea of having my test suite depending on a value that anyone is capable of changing in runtime (thus breaking all the time-related tests or at least creating flaky tests) dreads me.

So, given the trade-offs, I still value having explicit design. It may be a bit more verbose sometimes but it's simple, stable, and reliable.  

I hope you understand my PoV and why I believe this is not suitable for this lib. You are completely free to release such functionality in another package, though, and use it for your projects 😁

**Comment by ragboyjr** [comment]
Tbh, I’m more just picking your brain and wanting to start a discussion on the best way to approach this in general. I very much appreciate the thought and design you put into your packages. So I was trying to see if I’m missing something in the way that I design my entities and tests, or if the extra syntax is truly just something you have to deal with.
