### ISSUE TITLE
Consider different abstraction

### ISSUE THREAD

**Issue by fesor** [lcobucci/clock#4]
Instead of clock it's maybe more interesting to see time as stream of timestamps. So each next timestamp will be "now" or just same time stamp.

**Comment by lcobucci** [comment]
@fesor could you explain a bit more your thoughts?

**Comment by fesor** [comment]
I stole this idea from this article: [Beyond Mock Objects](http://blog.thecodewhisperer.com/permalink/beyond-mock-objects). I tried it and this fits more naturally that artificial `Clock`.

**Comment by lcobucci** [comment]
@fesor although I don't fully agree I must say that it's an interesting article, thanks!

I'd say that what we need to find is the right balance on where we should inject a clock and where we should simply pass the current time.

> The code doesn't want a clock; it wants a stream of timestamps. So give it a stream of timestamps. You could pass an InfiniteIterator of Timestamp objects (or whatever you call them in your programming language of choice). This represents a true abstraction, because it says, "My code needs some timestamps. I don't know how many it needs and I don't even care what they represent. My code just needs an endless stream of timestamps."

I haven't had a use case like this, so I'm a bit skeptical 😄 but as far as I understood it would be something like this:

```php
namespace Lcobucci\Clock;

use DateTimeImmutable;
use Iterator;

final class StreamClock implements Clock, Iterator
{
    /**
     * @var Clock
     */
    private $decorated;

    /**
     * @var DateTimeImmutable|null
     */
    private $now;

    public function __construct(Clock $decorated)
    {
        $this->decorated = $decorated;
    }

    public function now(): DateTimeImmutable
    {
        if ($this->now === null) {
            $this->next();
        }

        return $this->now;
    }

    public function current(): DateTimeImmutable
    {
        return $this->now();
    }

    public function next(): void
    {
        $this->now = $this->decorated->now();
    }

    public function valid(): bool
    {
        return true;
    }

    public function rewind(): void
    {
    }

    public function key(): string
    {
        return $this->now()->format('U.u');
    }
}
```

Did I get this right? 

With that you have this `InfiniteIterator of Timestamp objects (or whatever you call them in your programming language of choice)` but I fail to see how this fits more naturally in things... would you like to send a PR with your ideas?

**Comment by fesor** [comment]
> Did I get this right?

Yes.

> I fail to see how this fits more naturally in things

This highly depends on context. I just find that `now` is sometime not something that we really need.

For example. let's say that we are building scheduling system. At first things are simple, we just need to schedule.

```
// with clock
public function scheduleAppointment(Clock $clock): Appointment {
    return Appointment::new($this->id, $clock->now());
}
```

Then requirements changed, and we need to encounter time slots. So now it's not "now" but currently available time stots. In this case "now" doesn't really fits in our model since it not really "now" but more like "next available time". And we could encapsulate all rules of selection of available time slots into this stream.

```
use TimeStream as AvailableTime;
// ...
public function scheduleAppointment(AvailableTime $time): Appointment {
    return Appointment::new($this->id, $time->next());
}
```

There are also some cases with time reservation and concurrency, but any way. I think that this kind of things is not possible to ship as library since all of this highly depend on domain. Also I have few streams of time ranges, which is simplified a lot of code in my current project.

Probably I will close this issue. 

> so I'm a bit skeptical 

Probably I just don't like `now` :)

**Comment by lcobucci** [comment]
Humm I got your point and, yes, for your model `now()` is just useless because you're not dealing with a clock anymore but rather time slots - which is indeed something completely different (it might or not use a clock, though).

> There are also some cases with time reservation and concurrency, but any way. I think that this kind of things is not possible to ship as library since all of this highly depend on domain.

I agree 👍 

> Probably I will close this issue.

Thanks for the discussion!
