### ISSUE TITLE
Dependency lock on PHP 8  breaks other PHP 7.* compatible packages

### ISSUE THREAD

**Issue by satyago** [lcobucci/clock#400]
The new dependency on PHP 8 is breaking compatibility with older PHP versions on other packages such as `league/oauth2-server`.
This change should have probably been done on a major version, if this package should be seen as SemVer compatible.

Any package requiring this one or depending on the JWT package will breakm when allowing automatic minor version upgrades.

**Comment by driesvints** [comment]
@satyago updating dependencies during minor (or even patch) increments is allowed in SemVer: https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

Normally Composer should be able to prevent an upgrade from happening that isn't compatible. So I'm actually wondering why that specifically isn't happening.

**Comment by lcobucci** [comment]
@satyago I can't seem to reproduce the issue you're describing:

Having the following `composer.json` file:

```json
{
    "name": "test/app",
    "require": {
        "lcobucci/jwt": "^4.1"
    },
    "autoload": {
        "psr-4": {
            "Test\\App\\": "src/"
        }
    }
}
```

Composer does install the correct versions (when running on PHP 7.4):

```bash
$ php -v
PHP 7.4.25 (cli) (built: Oct 22 2021 17:55:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

$ composer install
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking lcobucci/clock (2.0.0)
  - Locking lcobucci/jwt (4.1.5)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading lcobucci/clock (2.0.0)
  - Downloading lcobucci/jwt (4.1.5)
  - Installing lcobucci/clock (2.0.0): Extracting archive
  - Installing lcobucci/jwt (4.1.5): Extracting archive
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

Everything works fine with `league/oauth2-server` too, btw:

```json
{
    "name": "test/app",
    "require": {
        "league/oauth2-server": "^8.3"
    },
    "autoload": {
        "psr-4": {
            "Test\\App\\": "src/"
        }
    }
}
```

```shell
$ php -v
PHP 7.4.25 (cli) (built: Oct 22 2021 17:55:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

$ composer install
Loading composer repositories with package information
Updating dependencies
Lock file operations: 7 installs, 0 updates, 0 removals
  - Locking defuse/php-encryption (v2.3.1)
  - Locking lcobucci/clock (2.0.0)
  - Locking lcobucci/jwt (4.1.5)
  - Locking league/event (2.2.0)
  - Locking league/oauth2-server (8.3.3)
  - Locking paragonie/random_compat (v9.99.100)
  - Locking psr/http-message (1.0.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing lcobucci/clock (2.0.0): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing league/event (2.2.0): Extracting archive
  - Installing lcobucci/jwt (4.1.5): Extracting archive
  - Installing paragonie/random_compat (v9.99.100): Extracting archive
  - Installing defuse/php-encryption (v2.3.1): Extracting archive
  - Installing league/oauth2-server (8.3.3): Extracting archive
1 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
3 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

**Comment by lcobucci** [comment]
Is it possible that you are creating the `composer.lock` on PHP 8.0 and trying to run `composer install` on PHP 7.4? If so, it won't work (unless you explicitly configure the platform `composer config platform.php 7.4`).

**Comment by satyago** [comment]
@driesvints thank you for taking a second look and sorry for bothering.
I was convinced changing dependencies on minor is a no-go, considering it is a breaking change and a conflict when said package combined with more open parent packages (in this case platform requirements) that don't lock in on a minor version.
In this case it being a chain between `laravel/telescope`➡️ `league/oauth2-server`➡️ `lcobucci/jwt`➡️ `lcobucci/clock`.

@lcobucci No, but you are right in asking whether I work on two systems / PHP versions.
The host is on `PHP 7.4.22` and the VM is still on `PHP 7.4.11`.

All I did was a normal `composer update` after merging our develop into an open feature branch.
On the VM this resulted in a memory issue, so I ran the composer update on the host, eventually having to run it as `composer update --ignore-platform-reqs --no-scripts` which usually didn't cause any issues but in this case did (my bad).
Then the plan was to proceed with `composer install` inside the VM, which then failed to generate the autoload files via `composer dump-autoload` (this is a Laravel 7.x app) due to the platform requirement.

Locking composer's platform config as you mentioned (via `composer config platform.php 7.4`) actually resolved the issue, but I wouldn't have expected this to be necessary.
It was an oversight on my end, but I have my doubts that my brain is working at full capacity today, I still am a little confused.
Also getting issues when running the app as it cannot find the `env` Class, usually available once the autoload successfully ran …

I'm not going to lie, today is a bad day and I'm a little ashamed bringing this up as it all seems so rudimentary.
Let's consider this as resolved — my deepest apologies !

I guess I owe you both a beer *(looking for the sponsor buttons …)*

**Comment by driesvints** [comment]
@satyago don't be so hard on yourself. Everyone can have a bad day, including us 😅 

Glad you got that figured out 👍  And don't worry about it 😉

**Comment by lcobucci** [comment]
@satyago no worries at all, we all have been there and feel your pain!

`--ignore-platform-reqs` can be quite tricky, I'd reaaaally recommend you to avoid relying on it as much as possible. Perhaps only the `--no-scripts` would have solved the memory issues on your end (then, locking wouldn't be needed indeed) 👍 

I hope your bad day ends soon and that you only have great days ahead ❤️
