### ISSUE TITLE
Syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by habib2013** [lcobucci/clock#405]
Syntax error, unexpected 'private' (T_PRIVATE), expecting variable (T_VARIABLE)
 On clock/src/SystemClock.php

**Comment by lcobucci** [comment]
@habib2013 it seems like you're trying to use this library in an unsupported PHP version. Please use composer to install the most appropriate version according to your system.
