### ISSUE TITLE
Consider tagging v1.1.1

### ISSUE THREAD

**Issue by 1ma** [lcobucci/clock#6]
There have been 3 merged PRs since the last release back in January. Please consider releasing a new minor version :slightly_smiling_face:

**Comment by lcobucci** [comment]
@1ma I didn't tag them yet because the only relevant merge is regarding the `.gitattributes` file (and also because I was focused handling other stuff). I plan to do some minor changes in the lib and will release v1.2.

Thanks for the reminder :+1:

**Comment by lcobucci** [comment]
@1ma v1.2.0 released, closing here :+1:
