### ISSUE TITLE
 DateTimeZone

### ISSUE THREAD

**Issue by meysam3** [lcobucci/clock#668]
hi , 
in my laravel app after login to get user information get the below error:
'syntax error, unexpected identifier "DateTimeZone", expecting variable'
vendor/lcobucci/clock/src/SystemClock.php  line 13
my timezone Asia/Tehran

**Comment by lcobucci** [comment]
@meysam3 as described in https://github.com/lcobucci/clock#usage, we expect an instance of the `DatimeZone` object when instantiating the `SystemClock` (with it's normal constructor):

```php
$clock = new SystemClock(new DateTimeZone('Asia/Tehran'));
 ```

You may also use the default timezone in your php.ini:

```php
$clock = SystemClock::fromSystemTimezone();
```

**Comment by bolence** [comment]
Hi, I still have a problem with the same issue and it's always on the same server. composer.json is the same as always. What could be a problem here?
Thanks.

**Comment by lcobucci** [comment]
> Hi, I still have a problem with the same issue and it's always on the same server. composer.json is the same as always. What could be a problem here?
> Thanks.

What's the timezone configured in php.ini? How are you instantiating the clock object?

**Comment by bolence** [comment]
It's empty. I just have the timezone in config.php in Laravel. I don't know for instantiating the Clock object, I even didn't install this package. I suppose it's a dependency for some other package. On 2 other servers is working out of the box with the same settings in php.ini.

**Comment by lcobucci** [comment]
And which versions do you have (php, this lib)? Not knowing how things are being instantiated makes it super hard for me to help you...

**Comment by bolence** [comment]
I have PHP 8.1 and lib v3.0.0. Sorry, the instance is in BearerTokenValidator.php, initJwtConfiguration function.

**Comment by lcobucci** [comment]
Those files aren't part of this lib, so I still can't help to point you to the correct direction without seeing how this lib is being used.

Can you share links?
