### ISSUE TITLE
PHP 8.3 Support

### ISSUE THREAD

**Issue by rajeshreeputra** [lcobucci/clock#677]
What's the plan to provide support for PHP 8.3, which is scheduled for release on November 23, 2023, with the first RC version set to be release on August 31, 2023.

**Comment by rajeshreeputra** [comment]
Created PR to check php 8.3 compatibility [PR](https://github.com/lcobucci/clock/pull/678). Please review.

**Comment by lcobucci** [comment]
Thanks for the PR @rajeshreeputra!
As mentioned on the PR, I want to avoiding releasing a **stable** version of this lib for an **unstable** PHP version.

There's nothing preventing us from testing the currently released versions using `--ignore-platform-req=php` when installing dependencies - this obviously assumes that you're using that approach to test your software on php 8.3.
