### ISSUE TITLE
Dependency hell - make the PHP requirement less strict ~8.2.0

### ISSUE THREAD

**Issue by vtsykun** [lcobucci/clock#680]
This package is very popular and has a large number of packages dependent on it. But at the same time it has very strict php requirement `>= 8.2.0,  < 8.3.0`. If I want to test my project (which depends on `lcobucci/clock`) on PHP 8.3 I won't be able to do it now. If I need to support different PHP version 7.4-8.2, I'll have a problem too. Also composer may downgrade this package to `2.2.0` on php 8.3.
Since there should be no backwards compatibility breaks until php 9.0, can you fix php requirement?

```
- ~8.2.0
+ ^8.2
#or 
+ >=8.2 
```

**Comment by jdreesen** [comment]
> Since there should be no backwards compatibility breaks until php 9.0, can you fix php requirement?

PHP does not adhere to SemVer, so this statement is likely not true.

**Comment by lcobucci** [comment]
> PHP does not adhere to SemVer, so this statement is likely not true. 

This is one of the main reasons why I'm very explicit with regards which version is supported.

> Also composer may downgrade this package to 2.2.0 on php 8.3.

This package is fully tested with php 8.3 using `composer install --ignore-platform-req=php`). You can use the same strategy to test your system. 

Now that we're in RC-2, I might release a new version (8.2 and 8.3).

> If I need to support different PHP version 7.4-8.2

You can also specify a range of versions for this package on your composer.json.

**Comment by inri13666** [comment]
@jdreesen & @lcobucci, seems we have an issue here https://getcomposer.org/doc/articles/versions.md#stability-constraints
It's ok, to use `--ignore-platform-req=php` for the testing, but ... what about prod envs ...
As I see the main question was in possibility to change the requirement from `~8.2.0` what means `8.2.[ANY_VERSION]` to `^8.2.0` what means `8.[ANY_VERSION]`.
```
  // ^ | doesn't allow breaking changes (major version fixed - following semver)
    "vendor/package": "^1.3.2", // >=1.3.2 <2.0.0
```

could you please describe the goal of strictly defined the PHP version?

**Comment by jdreesen** [comment]
The goal is to prevent problems with unsupported PHP version. As said, PHP does *not* adhere to SemVer and contains at least some breaking changes it almost every minor version. Thus, it's best to only allow those that are known to work.

> It's ok, to use --ignore-platform-req=php for the testing, but ... what about prod envs ...

Are you really going to run a beta/RC version of PHP in production?

**Comment by inri13666** [comment]
> Are you really going to run a beta/RC version of PHP in production?

yep, some times it's make me mad, but I need to have a chance to know if it works.
So, if it possible, please provide the goal for why I should use the exact version instead of range.
Do this package really contains bc breaks based on PHP version?
cc: @jdreesen

**Comment by jdreesen** [comment]
> Do this package really contains bc breaks based on PHP version?

We can't know until the next PHP version is released, that's why it's forbidden until we know ;)

> but I need to have a chance to know if it works.

Like @lcobucci already said: you can use `composer install --ignore-platform-req=php+` to see if it'll work.

**Comment by lcobucci** [comment]
Alright then... 
We have a new release: [v3.2.0-rc1](https://github.com/lcobucci/clock/releases/tag/3.2.0-rc1)

That should allow you to perform the tests you want in PHP 8.3 (need to add the `@rc` for `lcobucci/clock`, sure):

```sh
$ php -v
PHP 8.3.0RC3 (cli) (built: Sep 26 2023 12:07:34) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.3.0RC3, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.0RC3, Copyright (c), by Zend Technologies
    with Xdebug v3.3.0alpha2, Copyright (c) 2002-2023, by Derick Rethans

$ composer require lcobucci/clock:^3.1@rc
./composer.json has been updated
Running composer update lcobucci/clock
Loading composer repositories with package information
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking lcobucci/clock (3.2.0-rc1)
  - Locking psr/clock (1.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing psr/clock (1.0.0): Extracting archive
  - Installing lcobucci/clock (3.2.0-rc1): Extracting archive
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found.
```

Once PHP 8.3 is released, I'll ship the stable version :+1:
